title: Sector 5D
source_url: https://github.com/Sector5D/sector5d-wiki/

menu:
  - title: Home
    href: /
  - title: Servers
    href: /Servers
  - title: FAQ
    href: /FAQ
  - title: Webchat
    href: http://wbe04.mibbit.com/?settings=278e6d4d9fcb17bc10ac48082e6ff21d&server=irc.sector5d.org%3A%2B6697&channel=%23sector5d&hashtag=%23sector5d
